### PR TITLE
this should pass

### PR DESCRIPTION
**Pull request by muniter**
Hey

### CODE REVIEW

**Comment by muniter** [comment]
Well @dundargoc it runs here. But I'm also part of the neodundar org.  So that probably affects it. James merged the permission change. Now we just need someone to push to see if it works.

**Comment by muniter** [comment]
or if i need to put a cone of shame. Like the many times I fail at rebasing  😢

**Comment by dundargoc** [comment]
>  But I'm also part of the neodundar org

Shouldn't matter. Zeer/panders is part of neovim org and their jobs fail. Something is weeeeeeeeeird.

**Comment by muniter** [comment]
Maybe the neovim repo has stricter permissions than our forks, for CI runs? And therefore **called** workflows permissions needed to be listed/provided. Since the change fixed it. Your PR triggered the run an it worked https://github.com/neovim/neovim/actions/runs/2022310520

**Comment by dundargoc** [comment]
I could recreate the error. :confetti_ball: 

The permissions I had set was too lenient as you guessed.

**Comment by dundargoc** [comment]
Thanks for the help

**Pull request closed without merging**
