### PR TITLE
ci: test security flaw

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by muniter** [comment]
@dundargoc Isn't the previous state of the workflow also a security flaw. Since we are running gen_vimdoc.py resulting from the merge of the two branches?

**Comment by dundargoc** [comment]
Ye but it's with pull_request, not pull_request_target, meaning they only have read rights.

**Comment by muniter** [comment]
But the workflow explicitly says `pull_request: write` https://github.com/neovim/neovim/blob/a490db5ba819218e9188cbb51d885dbf3a194000/.github/workflows/api-docs-check.yml#L16

**Comment by muniter** [comment]
Also we miss you in matrix 😄 🤗

**Comment by dundargoc** [comment]
> But the workflow explicitly says `pull_request: write` [neovim/neovim@`a490db5`/.github/workflows/api-docs-check.yml#L16](https://github.com/neovim/neovim/blob/a490db5ba819218e9188cbb51d885dbf3a194000/.github/workflows/api-docs-check.yml#L16)

You fool. You absolute buffoon. Do you think logic works against github actions?

`pull_request` disallows all write permissions, *even* if you explicitly set permission to write. I totally didn't waste a lot of time trying to figure that one out. The permissions only become meaningful if you use `pull_request_target` (or as it turns out, `workflow_call` as well).

**Comment by muniter** [comment]
> You fool. You absolute buffoon. Do you think logic works against github actions?

Yes Sir, since I started learning them recently, I was thinking Github Actions followed the mother of all languages `C` were there's no undefined behavior and everything is facts an logics.

We definetly need ~shell~`ghactioncheck`

**Pull request closed without merging**
